# Generated by Django 5.1 on 2024-08-25 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quotation_number', models.CharField(blank=True, max_length=255)),
                ('quotation_date', models.DateField()),
                ('valid_till', models.DateField()),
                ('narration', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesQuotationMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('quotation_number', models.CharField(blank=True, max_length=255, null=True)),
                ('quotation_date', models.DateField()),
                ('valid_till', models.DateField()),
                ('customer', models.JSONField(null=True)),
                ('narration', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.JSONField(blank=True, null=True)),
                ('discount_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('discount_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('vat_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('vatable_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('non_vatable_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('grand_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('subtotal', models.FloatField(blank=True, default=0.0, null=True)),
                ('approved_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted_for_approval', 'Submitted for Approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='draft', max_length=100, null=True)),
                ('entry_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_user', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_comment', models.TextField(blank=True, null=True)),
                ('submit_for_approved_comment', models.TextField(blank=True, null=True)),
                ('submit_for_approved_date', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_date', models.DateField(blank=True, null=True)),
                ('cancelled_comment', models.TextField(blank=True, null=True)),
                ('submit_for_approval_date', models.DateField(blank=True, null=True)),
                ('used_status', models.CharField(choices=[('not used', 'Not Used'), ('partial', 'Partial'), ('complete', 'Complete')], default='not used', max_length=50)),
            ],
            options={
                'db_table': 'Quotation',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('uom', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('vat', models.CharField(blank=True, choices=[('0', '0% VAT'), ('13', '13% VAT'), ('non vatable', 'Non Vatable')], max_length=255)),
                ('vat_amount', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('item_total', models.FloatField(default=0)),
                ('remaining', models.FloatField(default=0)),
                ('used_status', models.CharField(choices=[('not used', 'Not Used'), ('partial', 'Partial'), ('complete', 'Complete')], default='not used', max_length=50)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='quotation.salesquotationmain')),
            ],
            options={
                'db_table': 'QuotationItem',
                'ordering': ['-id'],
            },
        ),
    ]
