# Generated by Django 5.1 on 2024-08-25 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('customer', models.JSONField(null=True)),
                ('narration', models.TextField(blank=True)),
                ('document', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(default=0)),
                ('non_vatable_amount', models.FloatField(default=0)),
                ('vatable_amount', models.FloatField(default=0)),
                ('vat_amount', models.FloatField(default=0)),
                ('discount_percentage', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('grand_total', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('payment_term', models.IntegerField(blank=True, null=True)),
                ('entry_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted_for_approval', 'Submitted for Approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='draft', max_length=50)),
                ('approval_user', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_comment', models.TextField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_date', models.DateField(blank=True, null=True)),
                ('cancelled_comment', models.TextField(blank=True, null=True)),
                ('submit_for_approval_comment', models.TextField(blank=True, null=True)),
                ('submit_for_approval_date', models.DateField(blank=True, null=True)),
                ('grn_verified', models.BooleanField(default=False)),
                ('invoice_created', models.BooleanField(default=False)),
                ('close', models.BooleanField(default=False)),
                ('invoice_status', models.CharField(choices=[('not used', 'Not Used'), ('partial', 'Partial'), ('complete', 'Complete')], default='not used', max_length=50)),
                ('delivery_note_status', models.CharField(choices=[('not used', 'Not Used'), ('partial', 'Partial'), ('complete', 'Complete')], default='not used', max_length=50)),
                ('approved_date_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SalesOrder',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('uom', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=0)),
                ('invoice_count', models.FloatField(default=0)),
                ('delivery_note_count', models.FloatField(default=0)),
                ('rate', models.FloatField()),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('discount_amount', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(default=0)),
                ('vat', models.CharField(blank=True, choices=[('0', '0% VAT'), ('13', '13% VAT'), ('non vatable', 'Non Vatable')], max_length=255)),
                ('vat_amount', models.FloatField(default=0)),
                ('item_total', models.FloatField(default=0)),
                ('invoice_status', models.CharField(choices=[('not used', 'Not Used'), ('partial', 'Partial'), ('complete', 'Complete')], default='not used', max_length=50)),
                ('delivery_note_status', models.CharField(choices=[('not used', 'Not Used'), ('partial', 'Partial'), ('complete', 'Complete')], default='not used', max_length=50)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='order_search.salesorder')),
            ],
            options={
                'db_table': 'SalesOrderItem',
                'ordering': ['-id'],
            },
        ),
    ]
